swagger: "2.0"

info:
  title: "WALKOFF"
  version: "1.0"

paths:
  /availablesubscriptions:
    get:
      tags:
        - System
      summary: Renders available subscription options
      description: ''
      operationId: server.controllers.system.display_possible_subscriptions
      produces:
        - application/json
      responses:
        '405':
          description: Invalid input